### ISSUE TITLE
More clearly mark domintro as non-normative

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#115]
We're using green boxes with short API descriptions as help for web developers, e.g., https://dom.spec.whatwg.org/#interface-customevent, but they continue to cause some confusion where implementers quote the boxes rather than the normative material. 

Instead of "Note" we could use "Introduction (non-normative)" or "For web developers (non-normative)", or maybe there's an even better idea?

cc @fantasai @tabatkins @zcorpan @terinjokes @domfarolino @shuangMoz

**Comment by shuangMoz** [comment]
I like "For web developers".

**Comment by domfarolino** [comment]
I agree with "For web developers (non-normative)", I like that the most. I guess with some more input perhaps we can start changing some domintro box titles?

**Comment by annevk** [comment]
@domfarolino it's a style sheet change at the moment so we'd end up changing it for all at once.

**Comment by tabatkins** [comment]
Ooh, yeah, I tried it myself, and I like the "For web developers (non-normative)" one. The style needs to be changed slightly, of course - if you just swap out the text, the length causes it to slightly overlap the text.

**Comment by annevk** [comment]
Changes I made: 
```css
dl.domintro::before { content: 'For web developers (non-normative)'; top:-0.8em }
dl.domintro { margin-top:2.5em }
```
Screenshot:
<img width="678" alt="screen shot 2017-11-17 at 16 38 19" src="https://user-images.githubusercontent.com/1544111/32955324-efb6409a-cbb5-11e7-9d4f-205be08f7865.png">

**Comment by annevk** [comment]
(That is, I fiddled with the inspector until it looked like that. If that's acceptable I'll create a PR.)

**Comment by domenic** [comment]
My suggestion:

```css
dl.domintro::before {
  content: 'For web developers (non-normative)';
  top: -0.8em;
  transform: none;
  left: -0.8em;
}
```
![screenshot-2017-11-17 fetch standard](https://user-images.githubusercontent.com/617481/32958434-7a260b54-cb8c-11e7-825e-e080564a10a7.png)
