### ISSUE TITLE
Make headers sticky?

### ISSUE THREAD

**Issue by domenic** [whatwg/whatwg.org#320]
See https://twitter.com/domenic/status/1266480528066256898 and https://gist.github.com/grassator/e76ec7775da5b1c14d125bc68e9a630d. It doesn't seem to work perfectly in general but maybe could be tweaked.

Some initial exploration makes me think that `position: sticky` was mostly designed to be used in conjunction with container elements, i.e. we'd have to restructure the spec to introduce `<section>` wrappers around each section of the spec.

**Comment by domenic** [comment]
Here was my initial attempt:

```css
h2 { position: sticky; top: 0; background: white; }
h3 { position: sticky; top: 28px; background: white; }
h4 { position: sticky; top: 56px; background: white; }
h5 { position: sticky; top: 84px; background: white; }
h6 { position: sticky; top: 112px; background: white; }
```

The problem is that since we don't have sectioning containers, everything sticks to the top forever. If you add backgrounds (as I did above) this can be OK as, for each N, only the topmost hN shows. However this breaks down when you're looking inside a h4 and have recently scrolled past a h5; that recent h5 still shows up, leading to scenarios like this:

![image](https://user-images.githubusercontent.com/617481/83307621-24746280-a1d3-11ea-9aab-2e97a960f882.png)

(Also, this really highlights how our section permalink markers are not lined up, boo.)
