### ISSUE TITLE
Restore the "new issue" feature

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#426]
I think for now the best course of action is to remove the floating "new issue" feature, but this CSS could possibly restore it:
```css
@keyframes new-issue {
  to {
    position:fixed;
    right:5px;
    bottom:5px;
    content:"File an issue";
  }
}

.head a[href$="/issues/new/choose"] {
  animation: new-issue forwards;
  animation-timeline: scroll();
  animation-range: 50vh 50vh;
}
```
This works quite well in Chromium, and in Gecko and WebKit it has the effect of making it permanently floating, which is a little weird when you're looking at the top of the document.

Also no browser supports the `content` property taking a string.
