### ISSUE TITLE
Customize nginx directory listings (e.g., use WHATWG green)

### ISSUE THREAD

**Issue by sideshowbarker** [whatwg/whatwg.org#91]
_From @sideshowbarker on September 12, 2017 8:50_

See https://github.com/whatwg/whatwg.org/issues/84#issuecomment-328783329. With some minimal CSS, we can customize the styling of nginx directory listings for, e.g., https://resources.whatwg.org/ and https://images.whatwg.org/ and https://n.whatwg.org/

_Copied from original issue: whatwg/resources.whatwg.org#64_

**Comment by sideshowbarker** [comment]
_From @annevk on September 12, 2017 8:55_

This should probably be in whatwg/whatwg.org as well as this repository is obsolete.

**Comment by annevk** [comment]
@sideshowbarker @foolip how about the following:
```css
html {
 font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  --whatwggreen: #3A7908;
}
body { 
  padding:0;
  margin:1em;
}
a {
 color: #00F;
}
a:visited {
 color: #0E388C;
}
a:hover, a:focus {
  color:var(--whatwggreen);
  text-decoration:none;
}
h1 {
  color:var(--whatwggreen);
}
table {
 border:1px solid #aaa;
 width:100%;
}
tr:nth-child(even) {
  background:#f4f4f4;
}
th,td {
  padding:0.5em;
}
th {
  text-align:left;
  font-weight:bold;
  background:#eee;
  border-bottom:1px solid #aaa;
}
th > a {
  text-decoration:none;
}
```
I basically created this in the browser.

It reuses fonts and styles from #153 for future consistency.
